Parking Manager: development/src/bankingtools.cpp File Reference
development/src/bankingtools.cpp File Reference
#include "bankingtools.h"
Functions
creditCardType getCreditCardType (const QString cardNumber)
bool chargeCreditCard (const QString cardNumber, const double charge)
Function Documentation
bool chargeCreditCard (const QString cardNumber, const double charge)
Definition at line 36 of file bankingtools.cpp.
References creditCardVisa, and getCreditCardType().
Referenced by InsertCardPage::validatePage().
creditCardType getCreditCardType (const QString cardNumber)
Definition at line 25 of file bankingtools.cpp.
References creditCardVisa.
Referenced by chargeCreditCard().