Parking Manager: ReportForm Class Reference
ReportForm Class Reference
#include <reportform.h>
Public Types
enum reportField {
Report_Id = 0, Report_Vehicle, Report_StartDate, Report_EndDate,
Report_StartTime, Report_EndTime, Report_Charge, Report_Customer
}
typedef enum
ReportForm::reportField reportField
Public Member Functions
ReportForm (QWidget *parent=0)
void done (const int result)
Private Slots
void custShowReport ()
void vehiShowReport ()
void dateShowReport ()
void showAllReport ()
void clearReport ()
Private Member Functions
void createReportPanel ()
void fixReportSize ()
Private Attributes
QSqlTableModel * tableModel
QWidget * reportPanel
QTableView * reportView
QLabel * custFilterLabel
QLabel * vehiFilterLabel
QLabel * fromDateFilterLabel
QLabel * toDateFilterLabel
QDateEdit * fromDateFilterEdit
QDateEdit * toDateFilterEdit
QLineEdit * custFilterEdit
QLineEdit * vehiFilterEdit
QPushButton * closeButton
QPushButton * dateShowButton
QPushButton * custShowButton
QPushButton * vehiShowButton
QPushButton * showAllButton
QPushButton * clearButton
QDialogButtonBox * buttonBox
Detailed Description
Definition at line 37 of file reportform.h.
Member Typedef Documentation
typedef enum ReportForm::reportField ReportForm::reportField
Member Enumeration Documentation
enum ReportForm::reportField
Enumerator:
Report_Id
Report_Vehicle
Report_StartDate
Report_EndDate
Report_StartTime
Report_EndTime
Report_Charge
Report_Customer
Definition at line 43 of file reportform.h.
Constructor & Destructor Documentation
ReportForm::ReportForm (QWidget * parent = 0)
Definition at line 29 of file reportform.cpp.
References buttonBox, clearButton, clearButtonStr, clearReport(), closeButton, closeButtonStr, createReportPanel(), reportPanel, reportView, repoWinTitleStr, showAllButton, showAllButtonStr, showAllReport(), and tableModel.
Member Function Documentation
void ReportForm::done (const int result)
Definition at line 70 of file reportform.cpp.
void ReportForm::custShowReport () [private, slot]
Definition at line 214 of file reportform.cpp.
References custFilterEdit, fixReportSize(), infoMsgTitleStr, sqlInjectCustStr, sqlInjectionRegExpStr, and tableModel.
Referenced by createReportPanel().
void ReportForm::vehiShowReport () [private, slot]
Definition at line 234 of file reportform.cpp.
References fixReportSize(), infoMsgTitleStr, sqlInjectionRegExpStr, sqlInjectVehiStr, tableModel, and vehiFilterEdit.
Referenced by createReportPanel().
void ReportForm::dateShowReport () [private, slot]
Definition at line 194 of file reportform.cpp.
References datesRelationStr, fixReportSize(), fromDateFilterEdit, infoMsgTitleStr, tableModel, and toDateFilterEdit.
Referenced by createReportPanel().
void ReportForm::showAllReport () [private, slot]
Definition at line 254 of file reportform.cpp.
References fixReportSize(), and tableModel.
Referenced by ReportForm().
void ReportForm::clearReport () [private, slot]
Definition at line 264 of file reportform.cpp.
References clearReportStr, infoMsgTitleStr, and tableModel.
Referenced by ReportForm().
void ReportForm::createReportPanel () [private]
Definition at line 77 of file reportform.cpp.
References chargeStr, custFilterEdit, custFilterLabel, customerLabelStr, customerStr, custShowButton, custShowReport(), dateShowButton, dateShowReport(), endDateStr, endTimeStr, fromDateFilterEdit, fromDateFilterLabel, fromDateLabelStr, Report_Charge, Report_Customer, Report_EndDate, Report_EndTime, Report_Id, Report_StartDate, Report_StartTime, Report_Vehicle, reportPanel, reportView, showButtonStr, startDateStr, startTimeStr, tableModel, toDateFilterEdit, toDateFilterLabel, toDateLabelStr, vehicleLabelStr, vehicleStr, vehiFilterEdit, vehiFilterLabel, vehiShowButton, and vehiShowReport().
Referenced by ReportForm().
void ReportForm::fixReportSize () [private]
Definition at line 286 of file reportform.cpp.
References reportView, and tableModel.
Referenced by custShowReport(), dateShowReport(), showAllReport(), and vehiShowReport().
Member Data Documentation
QSqlTableModel* ReportForm::tableModel [private]
Definition at line 68 of file reportform.h.
Referenced by clearReport(), createReportPanel(), custShowReport(), dateShowReport(), fixReportSize(), ReportForm(), showAllReport(), and vehiShowReport().
QWidget* ReportForm::reportPanel [private]
Definition at line 70 of file reportform.h.
Referenced by createReportPanel(), and ReportForm().
QTableView* ReportForm::reportView [private]
Definition at line 71 of file reportform.h.
Referenced by createReportPanel(), fixReportSize(), and ReportForm().
QLabel* ReportForm::custFilterLabel [private]
Definition at line 73 of file reportform.h.
Referenced by createReportPanel().
QLabel* ReportForm::vehiFilterLabel [private]
Definition at line 74 of file reportform.h.
Referenced by createReportPanel().
QLabel* ReportForm::fromDateFilterLabel [private]
Definition at line 75 of file reportform.h.
Referenced by createReportPanel().
QLabel* ReportForm::toDateFilterLabel [private]
Definition at line 76 of file reportform.h.
Referenced by createReportPanel().
QDateEdit* ReportForm::fromDateFilterEdit [private]
Definition at line 78 of file reportform.h.
Referenced by createReportPanel(), and dateShowReport().
QDateEdit* ReportForm::toDateFilterEdit [private]
Definition at line 79 of file reportform.h.
Referenced by createReportPanel(), and dateShowReport().
QLineEdit* ReportForm::custFilterEdit [private]
Definition at line 81 of file reportform.h.
Referenced by createReportPanel(), and custShowReport().
QLineEdit* ReportForm::vehiFilterEdit [private]
Definition at line 82 of file reportform.h.
Referenced by createReportPanel(), and vehiShowReport().
QPushButton* ReportForm::closeButton [private]
Definition at line 84 of file reportform.h.
Referenced by ReportForm().
QPushButton* ReportForm::dateShowButton [private]
Definition at line 85 of file reportform.h.
Referenced by createReportPanel().
QPushButton* ReportForm::custShowButton [private]
Definition at line 86 of file reportform.h.
Referenced by createReportPanel().
QPushButton* ReportForm::vehiShowButton [private]
Definition at line 87 of file reportform.h.
Referenced by createReportPanel().
QPushButton* ReportForm::showAllButton [private]
Definition at line 88 of file reportform.h.
Referenced by ReportForm().
QPushButton* ReportForm::clearButton [private]
Definition at line 89 of file reportform.h.
Referenced by ReportForm().
QDialogButtonBox* ReportForm::buttonBox [private]
Definition at line 91 of file reportform.h.
Referenced by ReportForm().
The documentation for this class was generated from the following files:
development/src/reportform.h
development/src/reportform.cpp