Parking Manager: development/src/paywizard.h File Reference
development/src/paywizard.h File Reference
#include <QWizard>
Classes
class PayWizard
class SelectPayWayPage
class InsertCashPage
class InsertCardPage
class CompletePage
Variables
static const QString wizardWinTitleStr = QObject::tr("Payment Transaction")
static const QString payWayTitleStr = QObject::tr("Payment Way")
static const QString inputCardTitleStr = QObject::tr("Credit Card Payment Way")
static const QString inputCashTitleStr = QObject::tr("Cash Payment Way")
static const QString completeTitleStr = QObject::tr("Charge Completed")
static const QString custChangeLabelStr = QObject::tr("Customer's change : ")
static const QString payChargeLabelStr = QObject::tr("Money you will be charged : ")
static const QString payWayCashLabelStr = QObject::tr("&Cash")
static const QString payWayCardLabelStr = QObject::tr("&Credit Card")
static const QString inputCashLabelStr = QObject::tr("&Input Money :")
static const QString inputCardLabelStr = QObject::tr("&Credit Card :")
static const QString notManyMoneyStr = QObject::tr("Please input enough money for the charge.")
static const QString cardNotChargedStr = QObject::tr("Unfortunately, credit card cannot be charged.")
static const QString cardChargedLabelStr = QObject::tr("The credit card has been charged.")
static const QString payWayTopLabelStr = QObject::tr("Please select a payment way in order to continue.")
static const QString payReceiptHtmlStr
Variable Documentation
const QString cardChargedLabelStr = QObject::tr("The credit card has been charged.") [static]
Definition at line 30 of file paywizard.h.
Referenced by CompletePage::initializePage().
const QString cardNotChargedStr = QObject::tr("Unfortunately, credit card cannot be charged.") [static]
Definition at line 29 of file paywizard.h.
Referenced by InsertCardPage::validatePage().
const QString completeTitleStr = QObject::tr("Charge Completed") [static]
Definition at line 18 of file paywizard.h.
Referenced by CompletePage::CompletePage().
const QString custChangeLabelStr = QObject::tr("Customer's change : ") [static]
Definition at line 20 of file paywizard.h.
Referenced by CompletePage::initializePage().
const QString inputCardLabelStr = QObject::tr("&Credit Card :") [static]
Definition at line 26 of file paywizard.h.
Referenced by InsertCardPage::InsertCardPage().
const QString inputCardTitleStr = QObject::tr("Credit Card Payment Way") [static]
Definition at line 16 of file paywizard.h.
Referenced by InsertCardPage::InsertCardPage().
const QString inputCashLabelStr = QObject::tr("&Input Money :") [static]
Definition at line 25 of file paywizard.h.
Referenced by InsertCashPage::InsertCashPage().
const QString inputCashTitleStr = QObject::tr("Cash Payment Way") [static]
Definition at line 17 of file paywizard.h.
Referenced by InsertCashPage::InsertCashPage().
const QString notManyMoneyStr = QObject::tr("Please input enough money for the charge.") [static]
Definition at line 28 of file paywizard.h.
Referenced by InsertCashPage::validatePage().
const QString payChargeLabelStr = QObject::tr("Money you will be charged : ") [static]
Definition at line 21 of file paywizard.h.
Referenced by InsertCardPage::initializePage(), and InsertCashPage::initializePage().
const QString payReceiptHtmlStr [static]
Initial value:
 QObject::tr(
        "<h2>%1 %2</h2>"
        "<p>Receipt for transaction payment.</p>"
        "<ul><li>Customer Name : <b>%3</b></li>"
        "<li>Date & Time : <b>%4</b></li>"
        "<li>Payment Charge : <b>%5</b></li></ul>")
Definition at line 33 of file paywizard.h.
Referenced by CompletePage::printButtonClicked().
const QString payWayCardLabelStr = QObject::tr("&Credit Card") [static]
Definition at line 24 of file paywizard.h.
Referenced by SelectPayWayPage::SelectPayWayPage().
const QString payWayCashLabelStr = QObject::tr("&Cash") [static]
Definition at line 23 of file paywizard.h.
Referenced by SelectPayWayPage::SelectPayWayPage().
const QString payWayTitleStr = QObject::tr("Payment Way") [static]
Definition at line 15 of file paywizard.h.
Referenced by SelectPayWayPage::SelectPayWayPage().
const QString payWayTopLabelStr = QObject::tr("Please select a payment way in order to continue.") [static]
Definition at line 31 of file paywizard.h.
Referenced by SelectPayWayPage::SelectPayWayPage().
const QString wizardWinTitleStr = QObject::tr("Payment Transaction") [static]
Definition at line 14 of file paywizard.h.
Referenced by PayWizard::PayWizard().