Parking Manager: development/src/globaldeclarations.h File Reference
development/src/globaldeclarations.h File Reference
#include <QtGui>
Enumerations
enum cardMemberType {
ErrorCardType = -1, NoCardType, SimpleCardType, MonthCardType,
YearCardType, CreditCardType
}
Variables
static const double MONTH_CARD_FEE = 100
static const double YEAR_CARD_FEE = 1000
static const QString sqlInjectionRegExpStr = "[" + QRegExp::escape("\'\"$*+?[]^{|};\\") + "]+"
static const QString numberRegExpStr = "^[0-9]+(,[0-9]+){0,1}$"
static const QString creditCardNumberMaskStr = "0000-0000-0000-0000;_"
static const QString dateTimeFormatStr = "dd-MM-yyyy, hh:mm:ss"
static const QString infoMsgTitleStr = QObject::tr("Application's Message")
static const QString nameLabelStr = QObject::tr("&Name :")
static const QString customerLabelStr = QObject::tr("&Customer :")
static const QString vehicleLabelStr = QObject::tr("&Vehicle :")
static const QString customerStr = QObject::tr("Customer")
static const QString vehicleStr = QObject::tr("Vehicle")
static const QString firstButtonStr = QObject::tr("<< &First")
static const QString previousButtonStr = QObject::tr("< &Previous")
static const QString nextButtonStr = QObject::tr("&Next >")
static const QString lastButtonStr = QObject::tr("&Last >>")
static const QString addButtonStr = QObject::tr("&Add")
static const QString deleteButtonStr = QObject::tr("&Delete")
static const QString closeButtonStr = QObject::tr("&Close")
static const QString printButtonStr = QObject::tr("&Print")
static const QString cantWriteSetsStr = QObject::tr("Application Cannot Use Settings!")
static const QString sqlInjectCustStr = QObject::tr("Please remove any character symbols from the customer name.")
static const QString sqlInjectVehiStr = QObject::tr("Please remove any character symbols from the vehicle name.")
static const QString appCopyright = QObject::tr("Copyright (C) 2010 Efstathios Chatzikyriakidis (contact@efxa.org)")
static const QString appName = QObject::tr("Parking Manager")
static const QString appVersion = QObject::tr("1.0")
static const QString appLicense
Enumeration Type Documentation
enum cardMemberType
Enumerator:
ErrorCardType
NoCardType
SimpleCardType
MonthCardType
YearCardType
CreditCardType
Definition at line 9 of file globaldeclarations.h.
Variable Documentation
const QString addButtonStr = QObject::tr("&Add") [static]
Definition at line 49 of file globaldeclarations.h.
Referenced by CustomerForm::CustomerForm(), and VehicleForm::VehicleForm().
const QString appCopyright = QObject::tr("Copyright (C) 2010 Efstathios Chatzikyriakidis (contact@efxa.org)") [static]
Definition at line 59 of file globaldeclarations.h.
Referenced by MainForm::handleAbout().
const QString appLicense [static]
Initial value:
 QObject::tr("This program is free software: you can redistribute it and/or modify "
                                                "it under the terms of the GNU General Public License as published by the "
                                                "Free Software Foundation, either version 3 of the License, or (at your "
                                                "option) any later version.")
Definition at line 63 of file globaldeclarations.h.
Referenced by MainForm::handleAbout().
const QString appName = QObject::tr("Parking Manager") [static]
Definition at line 60 of file globaldeclarations.h.
Referenced by createDBInstance(), MainForm::handleAbout(), MainForm::MainForm(), and CompletePage::printButtonClicked().
const QString appVersion = QObject::tr("1.0") [static]
Definition at line 61 of file globaldeclarations.h.
Referenced by MainForm::handleAbout(), and CompletePage::printButtonClicked().
const QString cantWriteSetsStr = QObject::tr("Application Cannot Use Settings!") [static]
Definition at line 55 of file globaldeclarations.h.
Referenced by MainForm::establishSettings(), and SettingsForm::writeSettings().
const QString closeButtonStr = QObject::tr("&Close") [static]
Definition at line 51 of file globaldeclarations.h.
Referenced by CustomerForm::CustomerForm(), ReportForm::ReportForm(), SettingsForm::SettingsForm(), TransactionForm::TransactionForm(), and VehicleForm::VehicleForm().
const QString creditCardNumberMaskStr = "0000-0000-0000-0000;_" [static]
Definition at line 29 of file globaldeclarations.h.
Referenced by InsertCardPage::InsertCardPage().
const QString customerLabelStr = QObject::tr("&Customer :") [static]
Definition at line 38 of file globaldeclarations.h.
Referenced by ReportForm::createReportPanel(), TransactionForm::TransactionForm(), and VehicleForm::VehicleForm().
const QString customerStr = QObject::tr("Customer") [static]
Definition at line 41 of file globaldeclarations.h.
Referenced by ReportForm::createReportPanel().
const QString dateTimeFormatStr = "dd-MM-yyyy, hh:mm:ss" [static]
Definition at line 32 of file globaldeclarations.h.
Referenced by CompletePage::printButtonClicked().
const QString deleteButtonStr = QObject::tr("&Delete") [static]
Definition at line 50 of file globaldeclarations.h.
Referenced by CustomerForm::CustomerForm(), TransactionForm::TransactionForm(), and VehicleForm::VehicleForm().
const QString firstButtonStr = QObject::tr("<< &First") [static]
Definition at line 44 of file globaldeclarations.h.
Referenced by TransactionForm::TransactionForm().
const QString infoMsgTitleStr = QObject::tr("Application's Message") [static]
Definition at line 35 of file globaldeclarations.h.
Referenced by CustomerForm::addCustomer(), CustomerForm::addEditCard(), VehicleForm::addVehicle(), TransactionForm::checkCardType(), ReportForm::clearReport(), TransactionForm::completePayment(), TransactionForm::completeTransaction(), ReportForm::custShowReport(), ReportForm::dateShowReport(), CustomerForm::deleteCustomer(), TransactionForm::deleteTransaction(), VehicleForm::deleteVehicle(), VehicleForm::done(), CustomerForm::done(), MainForm::establishSettings(), CustomerForm::handleCardType(), VehicleForm::transactionVehicle(), InsertCardPage::validatePage(), InsertCashPage::validatePage(), ReportForm::vehiShowReport(), and SettingsForm::writeSettings().
const QString lastButtonStr = QObject::tr("&Last >>") [static]
Definition at line 47 of file globaldeclarations.h.
Referenced by TransactionForm::TransactionForm().
const double MONTH_CARD_FEE = 100 [static]
Definition at line 19 of file globaldeclarations.h.
Referenced by CustomerForm::handleCardType().
const QString nameLabelStr = QObject::tr("&Name :") [static]
Definition at line 37 of file globaldeclarations.h.
Referenced by CustomerForm::CustomerForm(), and VehicleForm::VehicleForm().
const QString nextButtonStr = QObject::tr("&Next >") [static]
Definition at line 46 of file globaldeclarations.h.
Referenced by TransactionForm::TransactionForm().
const QString numberRegExpStr = "^[0-9]+(,[0-9]+){0,1}$" [static]
Definition at line 26 of file globaldeclarations.h.
Referenced by InsertCashPage::InsertCashPage().
const QString previousButtonStr = QObject::tr("< &Previous") [static]
Definition at line 45 of file globaldeclarations.h.
Referenced by TransactionForm::TransactionForm().
const QString printButtonStr = QObject::tr("&Print") [static]
Definition at line 53 of file globaldeclarations.h.
Referenced by CompletePage::setVisible().
const QString sqlInjectCustStr = QObject::tr("Please remove any character symbols from the customer name.") [static]
Definition at line 56 of file globaldeclarations.h.
Referenced by CustomerForm::addCustomer(), ReportForm::custShowReport(), and CustomerForm::done().
const QString sqlInjectionRegExpStr = "[" + QRegExp::escape("\'\"$*+?[]^{|};\\") + "]+" [static]
Definition at line 23 of file globaldeclarations.h.
Referenced by CustomerForm::addCustomer(), VehicleForm::addVehicle(), ReportForm::custShowReport(), VehicleForm::done(), CustomerForm::done(), and ReportForm::vehiShowReport().
const QString sqlInjectVehiStr = QObject::tr("Please remove any character symbols from the vehicle name.") [static]
Definition at line 57 of file globaldeclarations.h.
Referenced by VehicleForm::addVehicle(), VehicleForm::done(), and ReportForm::vehiShowReport().
const QString vehicleLabelStr = QObject::tr("&Vehicle :") [static]
Definition at line 39 of file globaldeclarations.h.
Referenced by ReportForm::createReportPanel(), and TransactionForm::TransactionForm().
const QString vehicleStr = QObject::tr("Vehicle") [static]
Definition at line 42 of file globaldeclarations.h.
Referenced by ReportForm::createReportPanel(), and MainForm::createVehiclePanel().
const double YEAR_CARD_FEE = 1000 [static]
Definition at line 20 of file globaldeclarations.h.
Referenced by CustomerForm::handleCardType().