Parking Manager: TransactionForm Class Reference
TransactionForm Class Reference
#include <transactionform.h>
Public Types
enum transactionField {
Transaction_Id = 0, Transaction_VehicleId, Transaction_CustomerId, Transaction_StartDate,
Transaction_StartTime
}
typedef enum
TransactionForm::transactionField transactionField
Public Member Functions
TransactionForm (const appSettings sets, QWidget *parent=0)
void done (const int result)
Private Slots
void deleteTransaction ()
void completeTransaction ()
Private Member Functions
int getCustomerId (const int tran_id)
int checkCardType (const int cust_id)
int calculateTime (const QDate start_date, const QDate end_date, const QTime start_time, const QTime end_time)
bool completePayment (const int card_type, const int cust_id, const QString cust_name, const double charge)
void storeInReport (const QString cust_name, const QString vehi_name, const QDate start_date, const QDate end_date, const QTime start_time, const QTime end_time, const double charge)
bool chargeCustomerCard (const int cust_id, const double charge)
double calculateCharge (const int card_type, const int time)
double getCardMoney (const int cust_id)
void lockGUI ()
void unlockGUI ()
void clearGUI ()
Private Attributes
appSettings sets
QSqlRelationalTableModel * tableModel
QDataWidgetMapper * mapper
QLabel * vehicleLabel
QLabel * customerLabel
QLabel * startDateLabel
QLabel * startTimeLabel
QLineEdit * vehicleEdit
QLineEdit * customerEdit
EmptyDateEdit * startDateEdit
EmptyTimeEdit * startTimeEdit
QPushButton * firstButton
QPushButton * previousButton
QPushButton * nextButton
QPushButton * lastButton
QPushButton * deleteButton
QPushButton * completeButton
QPushButton * closeButton
QDialogButtonBox * buttonBox
Detailed Description
Definition at line 37 of file transactionform.h.
Member Typedef Documentation
typedef enum TransactionForm::transactionField TransactionForm::transactionField
Member Enumeration Documentation
enum TransactionForm::transactionField
Enumerator:
Transaction_Id
Transaction_VehicleId
Transaction_CustomerId
Transaction_StartDate
Transaction_StartTime
Definition at line 43 of file transactionform.h.
Constructor & Destructor Documentation
TransactionForm::TransactionForm (const appSettings sets, QWidget * parent = 0)
Definition at line 32 of file transactionform.cpp.
References buttonBox, closeButton, closeButtonStr, completeButton, completeButtonStr, completeTransaction(), customerEdit, customerLabel, customerLabelStr, deleteButton, deleteButtonStr, deleteTransaction(), firstButton, firstButtonStr, lastButton, lastButtonStr, lockGUI(), mapper, nextButton, nextButtonStr, previousButton, previousButtonStr, startDateEdit, startDateLabel, startDateLabelStr, startTimeEdit, startTimeLabel, startTimeLabelStr, tableModel, Transaction_CustomerId, Transaction_StartDate, Transaction_StartTime, Transaction_VehicleId, tranWinTitleStr, vehicleEdit, vehicleLabel, and vehicleLabelStr.
Member Function Documentation
void TransactionForm::done (const int result)
Definition at line 168 of file transactionform.cpp.
References mapper.
void TransactionForm::deleteTransaction () [private, slot]
Definition at line 178 of file transactionform.cpp.
References clearGUI(), deleteTransactStr, infoMsgTitleStr, lockGUI(), mapper, and tableModel.
Referenced by TransactionForm().
void TransactionForm::completeTransaction () [private, slot]
Definition at line 210 of file transactionform.cpp.
References calculateCharge(), calculateTime(), checkCardType(), clearGUI(), completePayment(), completeTransactStr, ErrorCardType, getCustomerId(), infoMsgTitleStr, lockGUI(), mapper, storeInReport(), tableModel, Transaction_CustomerId, Transaction_Id, Transaction_StartDate, Transaction_StartTime, Transaction_VehicleId, and transactSuccessStr.
Referenced by TransactionForm().
int TransactionForm::getCustomerId (const int tran_id) [private]
Definition at line 292 of file transactionform.cpp.
Referenced by completeTransaction().
int TransactionForm::checkCardType (const int cust_id) [private]
Definition at line 366 of file transactionform.cpp.
References cardExpiredStr, ErrorCardType, infoMsgTitleStr, MonthCardType, and YearCardType.
Referenced by completeTransaction().
int TransactionForm::calculateTime (const QDate start_date, const QDate end_date, const QTime start_time, const QTime end_time) [private]
Definition at line 417 of file transactionform.cpp.
Referenced by completeTransaction().
bool TransactionForm::completePayment (const int card_type, const int cust_id, const QString cust_name, const double charge) [private]
Definition at line 476 of file transactionform.cpp.
References chargeCustomerCard(), CreditCardType, ErrorCardType, getCardMoney(), infoMsgTitleStr, isLessThan(), MonthCardType, NoCardType, notManyCardMoneyStr, SimpleCardType, and YearCardType.
Referenced by completeTransaction().
void TransactionForm::storeInReport (const QString cust_name, const QString vehi_name, const QDate start_date, const QDate end_date, const QTime start_time, const QTime end_time, const double charge) [private]
Definition at line 529 of file transactionform.cpp.
Referenced by completeTransaction().
bool TransactionForm::chargeCustomerCard (const int cust_id, const double charge) [private]
Definition at line 349 of file transactionform.cpp.
Referenced by completePayment().
double TransactionForm::calculateCharge (const int card_type, const int time) [private]
Definition at line 434 of file transactionform.cpp.
References appSettings::chargePerTimeslice, appSettings::chargePrecision, CreditCardType, ErrorCardType, MonthCardType, NoCardType, sets, SimpleCardType, appSettings::timeslice, and YearCardType.
Referenced by completeTransaction().
double TransactionForm::getCardMoney (const int cust_id) [private]
Definition at line 320 of file transactionform.cpp.
Referenced by completePayment().
void TransactionForm::lockGUI () [private]
Definition at line 554 of file transactionform.cpp.
References customerEdit, startDateEdit, startTimeEdit, and vehicleEdit.
Referenced by completeTransaction(), deleteTransaction(), and TransactionForm().
void TransactionForm::unlockGUI () [private]
Definition at line 563 of file transactionform.cpp.
References customerEdit, startDateEdit, startTimeEdit, and vehicleEdit.
void TransactionForm::clearGUI () [private]
Definition at line 572 of file transactionform.cpp.
References EmptyTimeEdit::clear(), EmptyDateEdit::clear(), customerEdit, startDateEdit, startTimeEdit, and vehicleEdit.
Referenced by completeTransaction(), and deleteTransaction().
Member Data Documentation
appSettings TransactionForm::sets [private]
Definition at line 83 of file transactionform.h.
Referenced by calculateCharge().
QSqlRelationalTableModel* TransactionForm::tableModel [private]
Definition at line 85 of file transactionform.h.
Referenced by completeTransaction(), deleteTransaction(), and TransactionForm().
QDataWidgetMapper* TransactionForm::mapper [private]
Definition at line 86 of file transactionform.h.
Referenced by completeTransaction(), deleteTransaction(), done(), and TransactionForm().
QLabel* TransactionForm::vehicleLabel [private]
Definition at line 88 of file transactionform.h.
Referenced by TransactionForm().
QLabel* TransactionForm::customerLabel [private]
Definition at line 89 of file transactionform.h.
Referenced by TransactionForm().
QLabel* TransactionForm::startDateLabel [private]
Definition at line 90 of file transactionform.h.
Referenced by TransactionForm().
QLabel* TransactionForm::startTimeLabel [private]
Definition at line 91 of file transactionform.h.
Referenced by TransactionForm().
QLineEdit* TransactionForm::vehicleEdit [private]
Definition at line 93 of file transactionform.h.
Referenced by clearGUI(), lockGUI(), TransactionForm(), and unlockGUI().
QLineEdit* TransactionForm::customerEdit [private]
Definition at line 94 of file transactionform.h.
Referenced by clearGUI(), lockGUI(), TransactionForm(), and unlockGUI().
EmptyDateEdit* TransactionForm::startDateEdit [private]
Definition at line 96 of file transactionform.h.
Referenced by clearGUI(), lockGUI(), TransactionForm(), and unlockGUI().
EmptyTimeEdit* TransactionForm::startTimeEdit [private]
Definition at line 97 of file transactionform.h.
Referenced by clearGUI(), lockGUI(), TransactionForm(), and unlockGUI().
QPushButton* TransactionForm::firstButton [private]
Definition at line 99 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::previousButton [private]
Definition at line 100 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::nextButton [private]
Definition at line 101 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::lastButton [private]
Definition at line 102 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::deleteButton [private]
Definition at line 103 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::completeButton [private]
Definition at line 104 of file transactionform.h.
Referenced by TransactionForm().
QPushButton* TransactionForm::closeButton [private]
Definition at line 105 of file transactionform.h.
Referenced by TransactionForm().
QDialogButtonBox* TransactionForm::buttonBox [private]
Definition at line 107 of file transactionform.h.
Referenced by TransactionForm().
The documentation for this class was generated from the following files:
development/src/transactionform.h
development/src/transactionform.cpp