Parking Manager: development/src/bankingtools.h File Reference
development/src/bankingtools.h File Reference
#include <QString>
Enumerations
enum creditCardType { creditCardError = -1, creditCardVisa, creditCardMasterCard }
Functions
creditCardType getCreditCardType (const QString cardNumber)
bool chargeCreditCard (const QString cardNumber, const double charge)
Enumeration Type Documentation
enum creditCardType
Enumerator:
creditCardError
creditCardVisa
creditCardMasterCard
Definition at line 9 of file bankingtools.h.
Function Documentation
bool chargeCreditCard (const QString cardNumber, const double charge)
Definition at line 36 of file bankingtools.cpp.
References creditCardVisa, and getCreditCardType().
Referenced by InsertCardPage::validatePage().
creditCardType getCreditCardType (const QString cardNumber)
Definition at line 25 of file bankingtools.cpp.
References creditCardVisa.
Referenced by chargeCreditCard().