Parking Manager: development/src/arithmetictools.cpp File Reference
development/src/arithmetictools.cpp File Reference
#include "arithmetictools.h"
Functions
bool isLessThan (const double a, const double b)
bool isGreaterThan (const double a, const double b)
Function Documentation
bool isGreaterThan (const double a, const double b)
Definition at line 31 of file arithmetictools.cpp.
Referenced by MainForm::establishSettings().
bool isLessThan (const double a, const double b)
Definition at line 25 of file arithmetictools.cpp.
Referenced by TransactionForm::completePayment(), MainForm::establishSettings(), and InsertCashPage::validatePage().