Parking Manager: EmptyTimeEdit Class Reference
EmptyTimeEdit Class Reference
#include <emptytimeedit.h>
Public Slots
void clear ()
void setTime (const QTime &time)
Public Member Functions
EmptyTimeEdit (const QTime &time, QWidget *parent=0)
EmptyTimeEdit (QWidget *parent=0)
~EmptyTimeEdit ()
QTime emptyTime () const
Properties
QTime emptyTime
Detailed Description
Definition at line 12 of file emptytimeedit.h.
Constructor & Destructor Documentation
EmptyTimeEdit::EmptyTimeEdit (const QTime & time, QWidget * parent = 0)
Definition at line 24 of file emptytimeedit.cpp.
References emptyTimeText.
EmptyTimeEdit::EmptyTimeEdit (QWidget * parent = 0)
Definition at line 29 of file emptytimeedit.cpp.
References emptyTimeText.
EmptyTimeEdit::~EmptyTimeEdit ()
Definition at line 34 of file emptytimeedit.cpp.
Member Function Documentation
QTime EmptyTimeEdit::emptyTime () const
void EmptyTimeEdit::clear () [slot]
Definition at line 38 of file emptytimeedit.cpp.
References setTime().
Referenced by TransactionForm::clearGUI().
void EmptyTimeEdit::setTime (const QTime & time) [slot]
Definition at line 54 of file emptytimeedit.cpp.
Referenced by clear().
Property Documentation
QTime EmptyTimeEdit::emptyTime [read, write]
Definition at line 16 of file emptytimeedit.h.
The documentation for this class was generated from the following files:
development/src/emptytimeedit.h
development/src/emptytimeedit.cpp