Parking Manager: EmptyDateEdit Class Reference
EmptyDateEdit Class Reference
#include <emptydateedit.h>
Public Slots
void clear ()
void setDate (const QDate &date)
Public Member Functions
EmptyDateEdit (const QDate &date, QWidget *parent=0)
EmptyDateEdit (QWidget *parent=0)
~EmptyDateEdit ()
QDate emptyDate () const
Properties
QDate emptyDate
Detailed Description
Definition at line 12 of file emptydateedit.h.
Constructor & Destructor Documentation
EmptyDateEdit::EmptyDateEdit (const QDate & date, QWidget * parent = 0)
Definition at line 24 of file emptydateedit.cpp.
References emptyDateText.
EmptyDateEdit::EmptyDateEdit (QWidget * parent = 0)
Definition at line 29 of file emptydateedit.cpp.
References emptyDateText.
EmptyDateEdit::~EmptyDateEdit ()
Definition at line 34 of file emptydateedit.cpp.
Member Function Documentation
QDate EmptyDateEdit::emptyDate () const
void EmptyDateEdit::clear () [slot]
Definition at line 38 of file emptydateedit.cpp.
References setDate().
Referenced by CustomerForm::addCustomer(), TransactionForm::clearGUI(), CustomerForm::clearGUI(), and CustomerForm::handleCardType().
void EmptyDateEdit::setDate (const QDate & date) [slot]
Definition at line 54 of file emptydateedit.cpp.
Referenced by clear(), and CustomerForm::handleCardType().
Property Documentation
QDate EmptyDateEdit::emptyDate [read, write]
Definition at line 16 of file emptydateedit.h.
The documentation for this class was generated from the following files:
development/src/emptydateedit.h
development/src/emptydateedit.cpp