Parking Manager: development/src/mainform.h File Reference
development/src/mainform.h File Reference
#include <QWidget>
#include "appsettings.h"
Classes
class MainForm
Variables
static const QString vehiclesButtonStr = QObject::tr("Manage &Vehicles")
static const QString customersButtonStr = QObject::tr("Manage &Customers")
static const QString transactsButtonStr = QObject::tr("Manage &Transactions")
static const QString reportButtonStr = QObject::tr("Transactions &Report")
static const QString guestVehiclesStr = QObject::tr("&Show Guest Vehicles")
static const QString quitButtonStr = QObject::tr("&Quit")
static const QString settingsButtonStr = QObject::tr("&Settings")
static const QString vehiclesOfStr = QObject::tr("Ve&hicles of %1")
static const QString vehiclesStr = QObject::tr("Ve&hicles")
static const QString customersStr = QObject::tr("&Customers")
static const QString nameStr = QObject::tr("Name")
static const QString cardStr = QObject::tr("Card Type")
static const QString phoneStr = QObject::tr("Phone")
static const QString descStr = QObject::tr("Description")
Variable Documentation
const QString cardStr = QObject::tr("Card Type") [static]
Definition at line 35 of file mainform.h.
Referenced by MainForm::createCustomerPanel().
const QString customersButtonStr = QObject::tr("Manage &Customers") [static]
Definition at line 23 of file mainform.h.
Referenced by MainForm::MainForm().
const QString customersStr = QObject::tr("&Customers") [static]
Definition at line 32 of file mainform.h.
Referenced by MainForm::createCustomerPanel().
const QString descStr = QObject::tr("Description") [static]
Definition at line 37 of file mainform.h.
Referenced by MainForm::createVehiclePanel().
const QString guestVehiclesStr = QObject::tr("&Show Guest Vehicles") [static]
Definition at line 26 of file mainform.h.
Referenced by MainForm::MainForm().
const QString nameStr = QObject::tr("Name") [static]
Definition at line 34 of file mainform.h.
Referenced by MainForm::createCustomerPanel().
const QString phoneStr = QObject::tr("Phone") [static]
Definition at line 36 of file mainform.h.
Referenced by MainForm::createCustomerPanel().
const QString quitButtonStr = QObject::tr("&Quit") [static]
Definition at line 27 of file mainform.h.
Referenced by MainForm::MainForm().
const QString reportButtonStr = QObject::tr("Transactions &Report") [static]
Definition at line 25 of file mainform.h.
Referenced by MainForm::MainForm().
const QString settingsButtonStr = QObject::tr("&Settings") [static]
Definition at line 28 of file mainform.h.
Referenced by MainForm::MainForm().
const QString transactsButtonStr = QObject::tr("Manage &Transactions") [static]
Definition at line 24 of file mainform.h.
Referenced by MainForm::MainForm().
const QString vehiclesButtonStr = QObject::tr("Manage &Vehicles") [static]
Definition at line 22 of file mainform.h.
Referenced by MainForm::MainForm().
const QString vehiclesOfStr = QObject::tr("Ve&hicles of %1") [static]
Definition at line 30 of file mainform.h.
Referenced by MainForm::updateVehicleView().
const QString vehiclesStr = QObject::tr("Ve&hicles") [static]
Definition at line 31 of file mainform.h.
Referenced by MainForm::createVehiclePanel(), MainForm::handleGuestVehicles(), and MainForm::updateVehicleView().