Parking Manager: development/src/vehicleform.h File Reference
development/src/vehicleform.h File Reference
#include <QDialog>
Classes
class VehicleForm
Variables
static const QString vehiWinTitleStr = QObject::tr("Manage Vehicles")
static const QString descLabelStr = QObject::tr("&Description :")
static const QString transactButtonStr = QObject::tr("&Start Transaction")
static const QString noCapacityInDBStr = QObject::tr("There is no more capacity for vehicles.")
static const QString vehicleReservedStr = QObject::tr("The vehicle is in the parking.")
static const QString deleteVehicleStr = QObject::tr("Do you want to delete the vehicle?")
Variable Documentation
const QString deleteVehicleStr = QObject::tr("Do you want to delete the vehicle?") [static]
Definition at line 26 of file vehicleform.h.
Referenced by VehicleForm::deleteVehicle().
const QString descLabelStr = QObject::tr("&Description :") [static]
Definition at line 20 of file vehicleform.h.
Referenced by VehicleForm::VehicleForm().
const QString noCapacityInDBStr = QObject::tr("There is no more capacity for vehicles.") [static]
Definition at line 24 of file vehicleform.h.
Referenced by VehicleForm::transactionVehicle().
const QString transactButtonStr = QObject::tr("&Start Transaction") [static]
Definition at line 22 of file vehicleform.h.
Referenced by VehicleForm::VehicleForm().
const QString vehicleReservedStr = QObject::tr("The vehicle is in the parking.") [static]
Definition at line 25 of file vehicleform.h.
Referenced by VehicleForm::deleteVehicle(), and VehicleForm::transactionVehicle().
const QString vehiWinTitleStr = QObject::tr("Manage Vehicles") [static]
Definition at line 18 of file vehicleform.h.
Referenced by VehicleForm::VehicleForm().