Parking Manager: development/src/main.cpp File Reference
development/src/main.cpp File Reference
#include <QtGui>
#include <QtSql>
#include <QTest>
#include <cstdlib>
#include "mainform.h"
#include "globaldeclarations.h"
Functions
static bool createDBConnection ()
static void createDBInstance ()
int main (int argc, char *argv[])
Variables
static const QString dbDriverStr = "QSQLITE"
static const QString dbFileNameStr = "database.db"
static const QString dbConnectErrorStr = QObject::tr("Database Connection Error")
static const QString dbDriverNotExistStr = QObject::tr("Database driver is not available.")
static const QString dbCannotOpenStr = QObject::tr("The database cannot open.")
static const QString dbCreationStr = QObject::tr("Creating a database instance...")
static const QString splashDBDriversStr = QObject::tr("Searching Available Database Drivers...")
static const QString splashDBConnectionStr = QObject::tr("Establishing Database Connection...")
static const QString splashSearchDBStr = QObject::tr("Searching Application's Database...")
static const QString splashCreateDBSchemaStr = QObject::tr("Creating Default Database Schema...")
static const QString splashFillDBStr = QObject::tr("Filling Database Default Data...")
static const QString splashAppStartStr = QObject::tr("Opening Parking Manager Application...")
static QSplashScreen * splash = NULL
static const Qt::Alignment topCenter = Qt::AlignHCenter | Qt::AlignTop
static const int SPLASH_TEXT_DELAY = 1500
static const int PBAR_MAX_STEPS = 8
Function Documentation
static bool createDBConnection () [static]
Definition at line 62 of file main.cpp.
References dbCannotOpenStr, dbConnectErrorStr, dbDriverNotExistStr, dbDriverStr, dbFileNameStr, splash, SPLASH_TEXT_DELAY, splashDBConnectionStr, splashDBDriversStr, splashSearchDBStr, and topCenter.
Referenced by main().
static void createDBInstance () [static]
Definition at line 106 of file main.cpp.
References appName, dbCreationStr, PBAR_MAX_STEPS, splash, SPLASH_TEXT_DELAY, splashCreateDBSchemaStr, splashFillDBStr, and topCenter.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 221 of file main.cpp.
References createDBConnection(), createDBInstance(), dbFileNameStr, splash, SPLASH_TEXT_DELAY, splashAppStartStr, and topCenter.
Variable Documentation
const QString dbCannotOpenStr = QObject::tr("The database cannot open.") [static]
Definition at line 38 of file main.cpp.
Referenced by createDBConnection().
const QString dbConnectErrorStr = QObject::tr("Database Connection Error") [static]
Definition at line 36 of file main.cpp.
Referenced by createDBConnection().
const QString dbCreationStr = QObject::tr("Creating a database instance...") [static]
Definition at line 39 of file main.cpp.
Referenced by createDBInstance().
const QString dbDriverNotExistStr = QObject::tr("Database driver is not available.") [static]
Definition at line 37 of file main.cpp.
Referenced by createDBConnection().
const QString dbDriverStr = "QSQLITE" [static]
Definition at line 32 of file main.cpp.
Referenced by createDBConnection().
const QString dbFileNameStr = "database.db" [static]
Definition at line 33 of file main.cpp.
Referenced by createDBConnection(), and main().
const int PBAR_MAX_STEPS = 8 [static]
Definition at line 58 of file main.cpp.
Referenced by createDBInstance().
QSplashScreen* splash = NULL [static]
Definition at line 49 of file main.cpp.
Referenced by createDBConnection(), createDBInstance(), and main().
const int SPLASH_TEXT_DELAY = 1500 [static]
Definition at line 55 of file main.cpp.
Referenced by createDBConnection(), createDBInstance(), and main().
const QString splashAppStartStr = QObject::tr("Opening Parking Manager Application...") [static]
Definition at line 46 of file main.cpp.
Referenced by main().
const QString splashCreateDBSchemaStr = QObject::tr("Creating Default Database Schema...") [static]
Definition at line 44 of file main.cpp.
Referenced by createDBInstance().
const QString splashDBConnectionStr = QObject::tr("Establishing Database Connection...") [static]
Definition at line 42 of file main.cpp.
Referenced by createDBConnection().
const QString splashDBDriversStr = QObject::tr("Searching Available Database Drivers...") [static]
Definition at line 41 of file main.cpp.
Referenced by createDBConnection().
const QString splashFillDBStr = QObject::tr("Filling Database Default Data...") [static]
Definition at line 45 of file main.cpp.
Referenced by createDBInstance().
const QString splashSearchDBStr = QObject::tr("Searching Application's Database...") [static]
Definition at line 43 of file main.cpp.
Referenced by createDBConnection().
const Qt::Alignment topCenter = Qt::AlignHCenter | Qt::AlignTop [static]
Definition at line 52 of file main.cpp.
Referenced by createDBConnection(), createDBInstance(), and main().