Parking Manager: MainForm Class Reference
MainForm Class Reference
#include <mainform.h>
Public Member Functions
MainForm ()
Private Slots
void updateVehicleView ()
void updateCustomerView ()
void editVehicles ()
void editCustomers ()
void editTransactions ()
void editSettings ()
void reportTransactions ()
void handleAbout ()
void handleGuestVehicles (const bool buttonPressed)
Private Member Functions
void createCustomerPanel ()
void createVehiclePanel ()
void establishSettings ()
Private Attributes
appSettings sets
QSqlRelationalTableModel * customerModel
QSqlRelationalTableModel * vehicleModel
QWidget * customerPanel
QWidget * vehiclePanel
QLabel * customerLabel
QLabel * vehicleLabel
QTableView * customerView
QTableView * vehicleView
QSplitter * splitter
QPushButton * editButtonVehicle
QPushButton * editButtonCustomer
QPushButton * editButtonTransaction
QPushButton * buttonReportTransaction
QPushButton * buttonGuestVehicles
QPushButton * settingsButton
QPushButton * quitButton
QToolButton * aboutButton
QDialogButtonBox * buttonBox
Detailed Description
Definition at line 40 of file mainform.h.
Constructor & Destructor Documentation
MainForm::MainForm ()
Definition at line 36 of file mainform.cpp.
References aboutButton, appName, buttonBox, buttonGuestVehicles, buttonReportTransaction, createCustomerPanel(), createVehiclePanel(), customerModel, customerPanel, customersButtonStr, customerView, editButtonCustomer, editButtonTransaction, editButtonVehicle, editCustomers(), editSettings(), editTransactions(), editVehicles(), establishSettings(), guestVehiclesStr, handleAbout(), handleGuestVehicles(), quitButton, quitButtonStr, reportButtonStr, reportTransactions(), settingsButton, settingsButtonStr, splitter, transactsButtonStr, vehicleModel, vehiclePanel, vehiclesButtonStr, and vehicleView.
Member Function Documentation
void MainForm::updateVehicleView () [private, slot]
Definition at line 130 of file mainform.cpp.
References CustomerForm::Customer_Id, CustomerForm::Customer_Name, customerModel, customerView, vehicleLabel, vehicleModel, vehiclesOfStr, vehiclesStr, and vehicleView.
Referenced by createCustomerPanel(), editVehicles(), and handleGuestVehicles().
void MainForm::updateCustomerView () [private, slot]
Definition at line 168 of file mainform.cpp.
References customerModel, and customerView.
Referenced by editCustomers().
void MainForm::editVehicles () [private, slot]
Definition at line 195 of file mainform.cpp.
References appSettings::parkingCapacity, sets, updateVehicleView(), VehicleForm::Vehicle_Id, vehicleModel, and vehicleView.
Referenced by MainForm().
void MainForm::editCustomers () [private, slot]
Definition at line 223 of file mainform.cpp.
References CustomerForm::Customer_Id, customerModel, customerView, and updateCustomerView().
Referenced by MainForm().
void MainForm::editTransactions () [private, slot]
Definition at line 251 of file mainform.cpp.
References sets.
Referenced by MainForm().
void MainForm::editSettings () [private, slot]
Definition at line 182 of file mainform.cpp.
References establishSettings(), and sets.
Referenced by MainForm().
void MainForm::reportTransactions () [private, slot]
Definition at line 261 of file mainform.cpp.
Referenced by MainForm().
void MainForm::handleAbout () [private, slot]
Definition at line 271 of file mainform.cpp.
References appCopyright, appLicense, appName, and appVersion.
Referenced by MainForm().
void MainForm::handleGuestVehicles (const bool buttonPressed) [private, slot]
Definition at line 281 of file mainform.cpp.
References updateVehicleView(), vehicleLabel, vehicleModel, vehiclesStr, and vehicleView.
Referenced by MainForm().
void MainForm::createCustomerPanel () [private]
Definition at line 360 of file mainform.cpp.
References cardStr, CustomerForm::Customer_Address, CustomerForm::Customer_CardDate, CustomerForm::Customer_CardId, CustomerForm::Customer_CardMoney, CustomerForm::Customer_City, CustomerForm::Customer_Email, CustomerForm::Customer_Id, CustomerForm::Customer_Name, CustomerForm::Customer_Phone, CustomerForm::Customer_State, customerLabel, customerModel, customerPanel, customersStr, customerView, nameStr, phoneStr, and updateVehicleView().
Referenced by MainForm().
void MainForm::createVehiclePanel () [private]
Definition at line 434 of file mainform.cpp.
References descStr, VehicleForm::Vehicle_CustomerId, VehicleForm::Vehicle_Description, VehicleForm::Vehicle_Id, VehicleForm::Vehicle_Name, vehicleLabel, vehicleModel, vehiclePanel, vehiclesStr, vehicleStr, and vehicleView.
Referenced by MainForm().
void MainForm::establishSettings () [private]
Definition at line 305 of file mainform.cpp.
References cantWriteSetsStr, appSettings::chargePerTimeslice, appSettings::chargePrecision, DEF_CHARGE_PER_TIMESLICE, DEF_CHARGE_PRECISION, DEF_PARKING_CAPACITY, DEF_TIMESLICE, infoMsgTitleStr, isGreaterThan(), isLessThan(), MAX_CHARGE_PER_TIMESLICE, MAX_CHARGE_PRECISION, MAX_PARKING_CAPACITY, MAX_TIMESLICE, MIN_CHARGE_PER_TIMESLICE, MIN_CHARGE_PRECISION, MIN_PARKING_CAPACITY, MIN_TIMESLICE, appSettings::parkingCapacity, sets, setsAppName, setsAppOrg, and appSettings::timeslice.
Referenced by editSettings(), and MainForm().
Member Data Documentation
appSettings MainForm::sets [private]
Definition at line 63 of file mainform.h.
Referenced by editSettings(), editTransactions(), editVehicles(), and establishSettings().
QSqlRelationalTableModel* MainForm::customerModel [private]
Definition at line 65 of file mainform.h.
Referenced by createCustomerPanel(), editCustomers(), MainForm(), updateCustomerView(), and updateVehicleView().
QSqlRelationalTableModel* MainForm::vehicleModel [private]
Definition at line 66 of file mainform.h.
Referenced by createVehiclePanel(), editVehicles(), handleGuestVehicles(), MainForm(), and updateVehicleView().
QWidget* MainForm::customerPanel [private]
Definition at line 68 of file mainform.h.
Referenced by createCustomerPanel(), and MainForm().
QWidget* MainForm::vehiclePanel [private]
Definition at line 69 of file mainform.h.
Referenced by createVehiclePanel(), and MainForm().
QLabel* MainForm::customerLabel [private]
Definition at line 71 of file mainform.h.
Referenced by createCustomerPanel().
QLabel* MainForm::vehicleLabel [private]
Definition at line 72 of file mainform.h.
Referenced by createVehiclePanel(), handleGuestVehicles(), and updateVehicleView().
QTableView* MainForm::customerView [private]
Definition at line 74 of file mainform.h.
Referenced by createCustomerPanel(), editCustomers(), MainForm(), updateCustomerView(), and updateVehicleView().
QTableView* MainForm::vehicleView [private]
Definition at line 75 of file mainform.h.
Referenced by createVehiclePanel(), editVehicles(), handleGuestVehicles(), MainForm(), and updateVehicleView().
QSplitter* MainForm::splitter [private]
Definition at line 77 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::editButtonVehicle [private]
Definition at line 79 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::editButtonCustomer [private]
Definition at line 80 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::editButtonTransaction [private]
Definition at line 81 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::buttonReportTransaction [private]
Definition at line 82 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::buttonGuestVehicles [private]
Definition at line 83 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::settingsButton [private]
Definition at line 84 of file mainform.h.
Referenced by MainForm().
QPushButton* MainForm::quitButton [private]
Definition at line 85 of file mainform.h.
Referenced by MainForm().
QToolButton* MainForm::aboutButton [private]
Definition at line 86 of file mainform.h.
Referenced by MainForm().
QDialogButtonBox* MainForm::buttonBox [private]
Definition at line 88 of file mainform.h.
Referenced by MainForm().
The documentation for this class was generated from the following files:
development/src/mainform.h
development/src/mainform.cpp