Parking Manager: development/src/reportform.h File Reference
development/src/reportform.h File Reference
#include <QDialog>
Classes
class ReportForm
Variables
static const QString repoWinTitleStr = QObject::tr("Transactions Report")
static const QString startDateStr = QObject::tr("Start Date")
static const QString endDateStr = QObject::tr("End Date")
static const QString startTimeStr = QObject::tr("Start Time")
static const QString endTimeStr = QObject::tr("End Time")
static const QString chargeStr = QObject::tr("Charge")
static const QString fromDateLabelStr = QObject::tr("&From Date :")
static const QString toDateLabelStr = QObject::tr("&To Date: ")
static const QString showButtonStr = QObject::tr("&Show")
static const QString clearButtonStr = QObject::tr("&Clear All")
static const QString showAllButtonStr = QObject::tr("&Show All")
static const QString datesRelationStr = QObject::tr("Please check if [To Date] is bigger than [From Date].")
static const QString clearReportStr = QObject::tr("Do you want to clear the report?")
Variable Documentation
const QString chargeStr = QObject::tr("Charge") [static]
Definition at line 24 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString clearButtonStr = QObject::tr("&Clear All") [static]
Definition at line 30 of file reportform.h.
Referenced by ReportForm::ReportForm().
const QString clearReportStr = QObject::tr("Do you want to clear the report?") [static]
Definition at line 34 of file reportform.h.
Referenced by ReportForm::clearReport().
const QString datesRelationStr = QObject::tr("Please check if [To Date] is bigger than [From Date].") [static]
Definition at line 33 of file reportform.h.
Referenced by ReportForm::dateShowReport().
const QString endDateStr = QObject::tr("End Date") [static]
Definition at line 21 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString endTimeStr = QObject::tr("End Time") [static]
Definition at line 23 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString fromDateLabelStr = QObject::tr("&From Date :") [static]
Definition at line 26 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString repoWinTitleStr = QObject::tr("Transactions Report") [static]
Definition at line 18 of file reportform.h.
Referenced by ReportForm::ReportForm().
const QString showAllButtonStr = QObject::tr("&Show All") [static]
Definition at line 31 of file reportform.h.
Referenced by ReportForm::ReportForm().
const QString showButtonStr = QObject::tr("&Show") [static]
Definition at line 29 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString startDateStr = QObject::tr("Start Date") [static]
Definition at line 20 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString startTimeStr = QObject::tr("Start Time") [static]
Definition at line 22 of file reportform.h.
Referenced by ReportForm::createReportPanel().
const QString toDateLabelStr = QObject::tr("&To Date: ") [static]
Definition at line 27 of file reportform.h.
Referenced by ReportForm::createReportPanel().