Parking Manager: development/src/settingsform.h File Reference
development/src/settingsform.h File Reference
#include <QDialog>
#include "appsettings.h"
Classes
class SettingsForm
Variables
static const QString setsWinTitleStr = QObject::tr("Manage Settings")
static const QString parkingCapacityLabelStr = QObject::tr("&Parking Capacity :")
static const QString chargeTimesliceLabelStr = QObject::tr("&Payment Timeslice :")
static const QString chargePerSliceLabelStr = QObject::tr("&Charge / Timeslice :")
static const QString chargePrecisionLabelStr = QObject::tr("&Charge Precision :")
static const QString saveButtonStr = QObject::tr("&Save")
Variable Documentation
const QString chargePerSliceLabelStr = QObject::tr("&Charge / Timeslice :") [static]
Definition at line 23 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().
const QString chargePrecisionLabelStr = QObject::tr("&Charge Precision :") [static]
Definition at line 24 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().
const QString chargeTimesliceLabelStr = QObject::tr("&Payment Timeslice :") [static]
Definition at line 22 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().
const QString parkingCapacityLabelStr = QObject::tr("&Parking Capacity :") [static]
Definition at line 21 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().
const QString saveButtonStr = QObject::tr("&Save") [static]
Definition at line 25 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().
const QString setsWinTitleStr = QObject::tr("Manage Settings") [static]
Definition at line 19 of file settingsform.h.
Referenced by SettingsForm::SettingsForm().