Parking Manager: development/src/customerform.h File Reference
development/src/customerform.h File Reference
#include <QDialog>
#include "emptydateedit.h"
Classes
class CustomerForm
Variables
static const QString custWinTitleStr = QObject::tr("Manage Customers")
static const QString addressLabelStr = QObject::tr("&Address :")
static const QString cityLabelStr = QObject::tr("&City :")
static const QString stateLabelStr = QObject::tr("&State :")
static const QString phoneLabelStr = QObject::tr("&Phone :")
static const QString emailLabelStr = QObject::tr("&Email :")
static const QString cardTypeLabelStr = QObject::tr("Card &Type :")
static const QString cardDateLabelStr = QObject::tr("Card &Date :")
static const QString cardMoneyLabelStr = QObject::tr("Card &Money :")
static const QString cardButtonStr = QObject::tr("&Add / Edit Card")
static const QString cardInputMoneyStr = QObject::tr("Please input money for the card :")
static const QString deleteCustomerStr = QObject::tr("Do you want to delete the customer?")
static const QString cardCreationStr = QObject::tr("Do you want to add / edit member card?")
Variable Documentation
const QString addressLabelStr = QObject::tr("&Address :") [static]
Definition at line 23 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString cardButtonStr = QObject::tr("&Add / Edit Card") [static]
Definition at line 32 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString cardCreationStr = QObject::tr("Do you want to add / edit member card?") [static]
Definition at line 36 of file customerform.h.
Referenced by CustomerForm::addEditCard().
const QString cardDateLabelStr = QObject::tr("Card &Date :") [static]
Definition at line 29 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString cardInputMoneyStr = QObject::tr("Please input money for the card :") [static]
Definition at line 34 of file customerform.h.
Referenced by CustomerForm::handleCardType().
const QString cardMoneyLabelStr = QObject::tr("Card &Money :") [static]
Definition at line 30 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString cardTypeLabelStr = QObject::tr("Card &Type :") [static]
Definition at line 28 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString cityLabelStr = QObject::tr("&City :") [static]
Definition at line 24 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString custWinTitleStr = QObject::tr("Manage Customers") [static]
Definition at line 21 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString deleteCustomerStr = QObject::tr("Do you want to delete the customer?") [static]
Definition at line 35 of file customerform.h.
Referenced by CustomerForm::deleteCustomer().
const QString emailLabelStr = QObject::tr("&Email :") [static]
Definition at line 27 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString phoneLabelStr = QObject::tr("&Phone :") [static]
Definition at line 26 of file customerform.h.
Referenced by CustomerForm::CustomerForm().
const QString stateLabelStr = QObject::tr("&State :") [static]
Definition at line 25 of file customerform.h.
Referenced by CustomerForm::CustomerForm().