Parking Manager: development/src/transactionform.h File Reference
development/src/transactionform.h File Reference
#include <QDialog>
#include "emptydateedit.h"
#include "emptytimeedit.h"
#include "globaldeclarations.h"
#include "appsettings.h"
Classes
class TransactionForm
Variables
static const QString tranWinTitleStr = QObject::tr("Manage Transactions")
static const QString startDateLabelStr = QObject::tr("&Start Date :")
static const QString startTimeLabelStr = QObject::tr("&Start Time :")
static const QString completeButtonStr = QObject::tr("&Complete Transaction")
static const QString deleteTransactStr = QObject::tr("Do you want to delete the transaction?")
static const QString completeTransactStr = QObject::tr("Do you want to complete the transaction?")
static const QString cardExpiredStr = QObject::tr("Customer's card is expired. Renew the card.")
static const QString notManyCardMoneyStr = QObject::tr("Not enough money in the card because charge is : ")
static const QString transactSuccessStr = QObject::tr("The transaction has been completed.")
Variable Documentation
const QString cardExpiredStr = QObject::tr("Customer's card is expired. Renew the card.") [static]
Definition at line 32 of file transactionform.h.
Referenced by TransactionForm::checkCardType().
const QString completeButtonStr = QObject::tr("&Complete Transaction") [static]
Definition at line 28 of file transactionform.h.
Referenced by TransactionForm::TransactionForm().
const QString completeTransactStr = QObject::tr("Do you want to complete the transaction?") [static]
Definition at line 31 of file transactionform.h.
Referenced by TransactionForm::completeTransaction().
const QString deleteTransactStr = QObject::tr("Do you want to delete the transaction?") [static]
Definition at line 30 of file transactionform.h.
Referenced by TransactionForm::deleteTransaction().
const QString notManyCardMoneyStr = QObject::tr("Not enough money in the card because charge is : ") [static]
Definition at line 33 of file transactionform.h.
Referenced by TransactionForm::completePayment().
const QString startDateLabelStr = QObject::tr("&Start Date :") [static]
Definition at line 25 of file transactionform.h.
Referenced by TransactionForm::TransactionForm().
const QString startTimeLabelStr = QObject::tr("&Start Time :") [static]
Definition at line 26 of file transactionform.h.
Referenced by TransactionForm::TransactionForm().
const QString transactSuccessStr = QObject::tr("The transaction has been completed.") [static]
Definition at line 34 of file transactionform.h.
Referenced by TransactionForm::completeTransaction().
const QString tranWinTitleStr = QObject::tr("Manage Transactions") [static]
Definition at line 23 of file transactionform.h.
Referenced by TransactionForm::TransactionForm().